import { useState, useEffect, useCallback, useRef, useMemo } from "react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { 
  Volume2, VolumeX, X, ChevronRight, ChevronLeft, ChevronDown, 
  SkipForward, Play, Pause, Sparkles, Settings2, Check,
  Mic2, Captions, Keyboard, Mail, Send, Rocket, Gift, 
  Heart, Star, Users, TrendingUp, Calendar, Zap
} from "lucide-react";
import { useLocation, useNavigate } from "react-router-dom";
import mascotImage from "@/assets/bamlead-mascot.png";
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover";
import { Slider } from "@/components/ui/slider";
import { Switch } from "@/components/ui/switch";
import { Label } from "@/components/ui/label";
import { toast } from "sonner";

interface VoiceOption {
  voice: SpeechSynthesisVoice;
  label: string;
  category: 'premium' | 'natural' | 'standard';
}

interface TourStep {
  id: string;
  page: string;
  element?: string;
  title: string;
  description: string;
  highlight?: boolean;
}

const TOUR_STEPS: TourStep[] = [
  {
    id: "welcome",
    page: "/",
    element: "[data-tour='hero']",
    title: "Welcome to BamLead! 🎉",
    description: "Well hello there, friend! I'm Bam, and I'll be your guide today. Just sit back and relax while I walk you through BamLead, the most advanced lead generation and AI outreach platform on the market. If you'd like to stop the tour at any time, just click the X button or Skip Tour. Alright, let's get started!"
  },
  {
    id: "autopilot-promo",
    page: "/",
    element: "[data-tour='autopilot-promo']",
    title: "AI Autopilot Campaigns",
    description: "Right at the top we showcase our AI Autopilot Campaign system. This is the fully autonomous mode where AI handles everything from lead discovery to email nurturing to proposal generation. You set the niche, the AI does the rest. It's available on our Autopilot and Unlimited plans."
  },
  {
    id: "intelligence-journey",
    page: "/",
    element: "[data-tour='intelligence-journey']",
    title: "The 4-Step Intelligence Pipeline",
    description: "Here's the Intelligence Journey, our interactive pipeline that shows exactly how BamLead works in four steps. Step one, choose your search mode. Step two, Search and Intelligence gathering. Step three, AI Strategy and Email composition. Step four, the AI Calling Hub. Each step shows what's included at each tier: Manual for Basic, Co-Pilot for Pro, and fully Autonomous for Autopilot."
  },
  {
    id: "super-ai",
    page: "/",
    element: "[data-tour='super-ai']",
    title: "Super AI Business Intelligence",
    description: "This is where BamLead really shines, my friend. Our Super AI Business Search generates a detailed 12-category intelligence report for every lead. Business Identity, Decision Maker Intelligence, Website Health, Online Visibility, Reputation and Reviews, AI Opportunity Analysis, Technographics, Marketing Behavior, Conversion Readiness, Buyer Intent, Competitive Pressure, and Communication Intelligence including best contact times. Every lead gets classified as Hot, Warm, or Cold."
  },
  {
    id: "synonym-expansion",
    page: "/",
    element: "[data-tour='synonym-expansion']",
    title: "Synonym AI Expansion Engine",
    description: "This interactive demo shows how a single keyword like mechanic gets expanded into 15 or more related niche terms, like auto repair, diesel technician, brake specialist, and so on. This is how we deliver the 2,000 plus leads promised in our higher tier plans. You search for one term and BamLead multiplies your reach across the entire niche."
  },
  {
    id: "agent-cards",
    page: "/",
    element: "[data-tour='agent-cards']",
    title: "Ready-to-Use Scanners",
    description: "Walk with me over here to meet your scanning agents. The GMB Scanner tracks down local businesses with Google My Business listings. And the Agency Lead Finder is built specifically for digital professionals, finding businesses with broken websites, weak social presence, and missing reviews. Both scanners work with our synonym expansion engine."
  },
  {
    id: "voice-calling",
    page: "/",
    element: "[data-tour='voice-calling']",
    title: "AI Voice Calling",
    description: "Here's something that sets BamLead apart from everyone else, AI Voice Calling. Our system can make calls to your leads using natural-sounding AI voices. You get call scripts generated by AI based on the lead's profile, live transcription during calls, call analytics, and follow-up scheduling. You can set up call queues, track call logs, and configure your Twilio phone number right from the dashboard."
  },
  {
    id: "ai-activation",
    page: "/",
    element: "[data-tour='ai-activation']",
    title: "When AI Activates",
    description: "This section shows you exactly when BamLead's AI kicks in during your workflow. Pre-Intent Detection predicts which leads will convert. Emotional State AI reads the mood behind interactions. The Sentiment Analyzer gauges customer sentiment in real time. During verification, AI validates emails and scores leads. During outreach, AI personalizes messages and predicts optimal send times. It's like having a team of experts working behind the scenes!"
  },
  {
    id: "revolutionary",
    page: "/",
    element: "[data-tour='revolutionary']",
    title: "Secret AI Weapons",
    description: "Allow me to show you the crown jewels. The Outcome Simulator lets you see predicted results before you send a campaign. The Psychological Profiler creates detailed customer personas. The Invisible Negotiator suggests real-time responses during conversations. The Founder Mirror matches you with leads who share your business philosophy. And the Reverse Lead Discovery flips the script, finding businesses that are already looking for YOUR services."
  },
  {
    id: "secret-ai",
    page: "/",
    element: "[data-tour='secret-ai']",
    title: "Secret AI Agents",
    description: "These are your behind-the-scenes AI agents, my friend. Each one handles a specialized task automatically. They work in the background while you focus on closing deals, performing tasks like market research, competitive analysis, lead enrichment, and niche intelligence gathering. Think of them as your invisible sales team."
  },
  {
    id: "roi-calculator",
    page: "/",
    element: "[data-tour='roi-calculator']",
    title: "ROI Calculator",
    description: "Before you invest, see exactly what you'll get back. Our interactive ROI Calculator lets you plug in your numbers, leads per month, average deal value, and conversion rate, and it shows you projected revenue. Most users see a 10x return on their BamLead subscription within the first month."
  },
  {
    id: "email-outreach",
    page: "/",
    element: "[data-tour='email-outreach']",
    title: "Email Outreach System",
    description: "Now let me show you something truly special, the email outreach system. You get access to over 60 professionally designed, high-converting email templates across industries like Web Design, Local Services, Insurance, Medical, Education, and B2B. Our AI personalizes content for each lead automatically. You can schedule sends at optimal times, track opens and replies in real time, and manage entire campaigns from one dashboard."
  },
  {
    id: "mailbox-demo",
    page: "/mailbox-demo",
    title: "Mailbox & AI Autopilot Demo",
    description: "Let me take you to the interactive Mailbox Demo. This is where you can see the full mailbox experience including the AI Strategy Brain, drip sequences, document generation, and the Autopilot campaign flow. The Brain generates campaign strategies based on your leads, and the sequence builder creates automated 7-step follow-up sequences. You can explore everything here without needing an account."
  },
  {
    id: "closeloop",
    page: "/closeloop",
    title: "CloseLoop — Full Sales Pipeline",
    description: "Now let me show you CloseLoop, our end-to-end sales pipeline manager. Track every lead from first contact to closed deal. Manage proposals, send contracts for digital signing, and monitor your conversion rates. It's the complete close-the-deal toolkit that turns your leads into revenue."
  },
  {
    id: "pricing-cta",
    page: "/pricing",
    title: "Flexible Pricing Plans",
    description: "Let me walk you through our pricing. We have five tiers designed for every stage of your business. The Free plan lets you try everything with limited daily searches. Basic at 49 dollars per month gives you 30 searches per day and AI-assisted email writing. Pro at 99 dollars per month unlocks 200 searches per day, auto follow-up sequences, and smart response detection. Autopilot at 249 dollars per month lets AI handle everything autonomously. And Unlimited at 999 dollars per month includes a dedicated AI Sales Brain and managed services."
  },
  {
    id: "features-page",
    page: "/features",
    title: "Features Overview",
    description: "This page gives you a clean summary of all BamLead's core features. Smart business search, website analysis, mobile responsiveness checking, SEO issue detection, lead scoring, and platform detection. It's a great reference page to bookmark and share with your team."
  },
  {
    id: "finish",
    page: "/",
    title: "You're All Set! 🚀",
    description: "Well, that concludes our tour! You've seen the AI Autopilot campaigns, the 4-step Intelligence Pipeline, Super AI reports with 12 categories, the Synonym Expansion engine, AI Voice Calling, secret AI agents, the ROI Calculator, 60 plus email templates, the Mailbox with the AI Strategy Brain, CloseLoop for closing deals, and our flexible pricing. Remember, you can start with a free plan to test everything. Best of luck with your lead hunting, my friend! I'll be right here if you need me."
  }
];

const STORAGE_KEY = "bamlead_tour_completed";
const TOUR_DISABLED_KEY = "bamlead_tour_disabled";

// Export function to start tour from anywhere
export const startTourManually = () => {
  localStorage.removeItem(STORAGE_KEY);
  window.dispatchEvent(new CustomEvent('start-tour'));
};

// Voice settings storage key
const VOICE_SETTINGS_KEY = "bamlead_voice_settings";

export default function AITourGuide() {
  const [isFirstVisit, setIsFirstVisit] = useState(false);
  const [showTour, setShowTour] = useState(false);
  const [currentStepIndex, setCurrentStepIndex] = useState(0);
  const [isSpeaking, setIsSpeaking] = useState(false);
  const [isPaused, setIsPaused] = useState(false);
  const [tourDisabled, setTourDisabled] = useState(false);
  const [mascotPosition, setMascotPosition] = useState({ x: 0, y: 0 });
  const [isWalking, setIsWalking] = useState(false);
  const [isDemoMinimized, setIsDemoMinimized] = useState(false);
  const [isCollapsed, setIsCollapsed] = useState(false);
  const [showHint, setShowHint] = useState(true);
  const [dragPosition, setDragPosition] = useState<{ x: number; y: number } | null>(null);
  const isDraggingRef = useRef(false);
  const dragOffsetRef = useRef({ x: 0, y: 0 });
  
  // Voice settings state
  const [availableVoices, setAvailableVoices] = useState<VoiceOption[]>([]);
  const [selectedVoiceIndex, setSelectedVoiceIndex] = useState(0);
  const [speechRate, setSpeechRate] = useState(1.0);
  const [showSubtitles, setShowSubtitles] = useState(true);
  const [showVoiceSettings, setShowVoiceSettings] = useState(false);
  const [isTestingVoice, setIsTestingVoice] = useState(false);
  
  // Auto-start countdown state (moved here to avoid hooks-order issues)
  const [countdown, setCountdown] = useState(3);
  const [countdownPaused, setCountdownPaused] = useState(false);
  const countdownRef = useRef<NodeJS.Timeout | null>(null);
  
  const speechRef = useRef<SpeechSynthesisUtterance | null>(null);
  const didCheckFirstVisitRef = useRef(false);
  const location = useLocation();
  const navigate = useNavigate();

  const currentStep = TOUR_STEPS[currentStepIndex];
  const hideFloatingDemoButton = useMemo(() => {
    const path = location.pathname;
    return (
      path.startsWith("/dashboard") ||
      path.startsWith("/admin") ||
      path.startsWith("/auth") ||
      path.startsWith("/verify-email") ||
      path.startsWith("/forgot-password") ||
      path.startsWith("/reset-password")
    );
  }, [location.pathname]);

  // Check if first visit
  useEffect(() => {
    if (didCheckFirstVisitRef.current) return;
    didCheckFirstVisitRef.current = true;

    const completed = localStorage.getItem(STORAGE_KEY);
    const disabled = localStorage.getItem(TOUR_DISABLED_KEY);
    
    if (disabled === "true") {
      setTourDisabled(true);
      return;
    }

    if (!completed && location.pathname === "/") {
      setIsFirstVisit(true);
      setTimeout(() => setShowTour(true), 1500);
    }
  }, [location.pathname]);

  // Listen for manual tour start
  useEffect(() => {
    const handleStartTour = () => {
      setTourDisabled(false);
      setIsFirstVisit(true);
      setShowTour(false);
      setCurrentStepIndex(0);
      if (location.pathname !== "/") {
        navigate("/");
      }
      setTimeout(() => setShowTour(true), 500);
    };

    window.addEventListener('start-tour', handleStartTour);
    return () => window.removeEventListener('start-tour', handleStartTour);
  }, [location.pathname, navigate]);

  // Categorize and organize available voices
  const categorizeVoices = useCallback((): VoiceOption[] => {
    if (!("speechSynthesis" in window)) return [];
    
    const voices = window.speechSynthesis.getVoices();
    const englishVoices = voices.filter(v => v.lang.startsWith("en"));
    
    const categorized: VoiceOption[] = [];
    
    // Premium voices (Natural, Premium, Enhanced in name)
    englishVoices.forEach(voice => {
      if (voice.name.includes("Natural") || voice.name.includes("Premium") || voice.name.includes("Enhanced")) {
        categorized.push({
          voice,
          label: voice.name.replace(" (Natural)", "").replace(" (Premium)", ""),
          category: 'premium'
        });
      }
    });
    
    // Natural-sounding voices (specific known good ones)
    const naturalNames = ["Aaron", "Evan", "Daniel", "Samantha", "Karen", "Moira", "Rishi"];
    englishVoices.forEach(voice => {
      if (naturalNames.some(name => voice.name.includes(name)) && !categorized.find(v => v.voice === voice)) {
        categorized.push({
          voice,
          label: voice.name,
          category: 'natural'
        });
      }
    });
    
    // Standard voices (everything else, excluding novelty)
    englishVoices.forEach(voice => {
      if (!categorized.find(v => v.voice === voice) && 
          !voice.name.includes("Novelty") && 
          !voice.name.includes("Zarvox") &&
          !voice.name.includes("Whisper") &&
          !voice.name.includes("Trinoids")) {
        categorized.push({
          voice,
          label: voice.name,
          category: 'standard'
        });
      }
    });
    
    return categorized;
  }, []);

  // Load and set voices
  useEffect(() => {
    const loadVoices = () => {
      const voices = categorizeVoices();
      setAvailableVoices(voices);
      
      // Load saved settings
      const savedSettings = localStorage.getItem(VOICE_SETTINGS_KEY);
      if (savedSettings) {
        try {
          const { voiceName, rate, subtitles } = JSON.parse(savedSettings);
          const savedIndex = voices.findIndex(v => v.voice.name === voiceName);
          if (savedIndex >= 0) setSelectedVoiceIndex(savedIndex);
          if (rate) setSpeechRate(rate);
          if (subtitles !== undefined) setShowSubtitles(subtitles);
        } catch (e) {
          console.log("Could not load voice settings");
        }
      }
    };

    if ("speechSynthesis" in window) {
      window.speechSynthesis.getVoices();
      loadVoices();
      window.speechSynthesis.onvoiceschanged = loadVoices;
    }

    return () => {
      if ("speechSynthesis" in window) {
        window.speechSynthesis.cancel();
      }
    };
  }, [categorizeVoices]);

  // Save voice settings when changed
  useEffect(() => {
    if (availableVoices.length > 0) {
      const settings = {
        voiceName: availableVoices[selectedVoiceIndex]?.voice.name,
        rate: speechRate,
        subtitles: showSubtitles
      };
      localStorage.setItem(VOICE_SETTINGS_KEY, JSON.stringify(settings));
    }
  }, [selectedVoiceIndex, speechRate, showSubtitles, availableVoices]);

  // Get selected voice
  const getSelectedVoice = useCallback(() => {
    if (availableVoices.length === 0) return null;
    return availableVoices[selectedVoiceIndex]?.voice || availableVoices[0]?.voice || null;
  }, [availableVoices, selectedVoiceIndex]);

  // Track if we should auto-advance (set by speak, cleared on manual navigation)
  const autoAdvanceRef = useRef(true);

  // Speak the current step with selected voice and auto-advance when done
  const speak = useCallback((text: string, shouldAutoAdvance = true) => {
    if (!("speechSynthesis" in window)) return;
    
    window.speechSynthesis.cancel();
    autoAdvanceRef.current = shouldAutoAdvance;
    
    const utterance = new SpeechSynthesisUtterance(text);
    utterance.rate = speechRate;
    utterance.pitch = 1.0;
    utterance.volume = 1;
    
    const selectedVoice = getSelectedVoice();
    if (selectedVoice) {
      utterance.voice = selectedVoice;
    }

    utterance.onstart = () => setIsSpeaking(true);
    utterance.onend = () => {
      setIsSpeaking(false);
      // Auto-advance to next step after speech ends
      if (autoAdvanceRef.current) {
        setTimeout(() => {
          setCurrentStepIndex(prev => {
            if (prev < TOUR_STEPS.length - 1) {
              return prev + 1;
            } else {
              // Tour complete
              localStorage.setItem(STORAGE_KEY, "true");
              setShowTour(false);
              setIsFirstVisit(false);
              return prev;
            }
          });
        }, 800); // Small pause before next step
      }
    };
    utterance.onerror = () => setIsSpeaking(false);

    speechRef.current = utterance;
    window.speechSynthesis.speak(utterance);
  }, [getSelectedVoice, speechRate]);

  // Test voice with sample text
  const testVoice = useCallback(() => {
    if (!("speechSynthesis" in window)) return;
    
    setIsTestingVoice(true);
    window.speechSynthesis.cancel();
    
    const testText = "Hey there! I'm Bam, your friendly guide. How does this voice sound to you?";
    const utterance = new SpeechSynthesisUtterance(testText);
    utterance.rate = speechRate;
    utterance.pitch = 1.0;
    utterance.volume = 1;
    
    const selectedVoice = getSelectedVoice();
    if (selectedVoice) {
      utterance.voice = selectedVoice;
    }

    utterance.onend = () => setIsTestingVoice(false);
    utterance.onerror = () => setIsTestingVoice(false);

    window.speechSynthesis.speak(utterance);
    toast.success("Testing voice...", { duration: 2000 });
  }, [getSelectedVoice, speechRate]);

  // Stop speaking
  const stopSpeaking = useCallback(() => {
    if ("speechSynthesis" in window) {
      window.speechSynthesis.cancel();
    }
    setIsSpeaking(false);
    setIsPaused(false);
  }, []);

  // Toggle pause/resume
  const togglePause = useCallback(() => {
    if (!("speechSynthesis" in window)) return;
    
    if (isPaused) {
      window.speechSynthesis.resume();
      setIsPaused(false);
    } else {
      window.speechSynthesis.pause();
      setIsPaused(true);
    }
  }, [isPaused]);

  // Move Bam to element
  const moveMascotToElement = useCallback((elementSelector?: string) => {
    setIsWalking(true);
    
    if (elementSelector) {
      const el = document.querySelector(elementSelector);
      if (el) {
        const rect = el.getBoundingClientRect();
        const scrollY = window.scrollY;
        
        // Position Bam next to the element (left side)
        setMascotPosition({
          x: Math.max(20, rect.left - 100),
          y: rect.top + scrollY + (rect.height / 2) - 60
        });
      }
    } else {
      // Default position for welcome/finish steps (center top)
      setMascotPosition({
        x: window.innerWidth / 2 - 60,
        y: window.scrollY + 200
      });
    }

    setTimeout(() => setIsWalking(false), 800);
  }, []);

  // Navigate to step (the useEffect handles the rest)
  const goToStep = useCallback((index: number, disableAutoAdvance = false) => {
    const step = TOUR_STEPS[index];
    if (!step) return;

    stopSpeaking();
    if (disableAutoAdvance) {
      autoAdvanceRef.current = false;
    }
    setCurrentStepIndex(index);
  }, [stopSpeaking]);

  // Start tour
  const startTour = useCallback(() => {
    autoAdvanceRef.current = true;
    setShowTour(true);
    setCurrentStepIndex(0);
  }, []);

  // Complete tour
  const completeTour = useCallback(() => {
    stopSpeaking();
    localStorage.setItem(STORAGE_KEY, "true");
    setShowTour(false);
    setIsFirstVisit(false);
    if (location.pathname !== "/") {
      navigate("/");
    }
  }, [location.pathname, navigate, stopSpeaking]);

  // Next step (manual - disables auto-advance)
  const nextStep = useCallback(() => {
    if (currentStepIndex < TOUR_STEPS.length - 1) {
      goToStep(currentStepIndex + 1, true);
    } else {
      completeTour();
    }
  }, [currentStepIndex, goToStep, completeTour]);

  // Previous step (manual - disables auto-advance)
  const prevStep = useCallback(() => {
    if (currentStepIndex > 0) {
      goToStep(currentStepIndex - 1, true);
    }
  }, [currentStepIndex, goToStep]);

  // Disable tour permanently
  const disableTour = useCallback(() => {
    stopSpeaking();
    localStorage.setItem(TOUR_DISABLED_KEY, "true");
    localStorage.setItem(STORAGE_KEY, "true");
    setTourDisabled(true);
    setShowTour(false);
    setIsFirstVisit(false);
  }, [stopSpeaking]);

  // Skip tour
  const skipTour = useCallback(() => {
    completeTour();
  }, [completeTour]);

  // Keyboard shortcuts
  useEffect(() => {
    if (!showTour) return;

    const handleKeyDown = (e: KeyboardEvent) => {
      // Ignore if typing in input
      if (e.target instanceof HTMLInputElement || e.target instanceof HTMLTextAreaElement) return;

      switch (e.key) {
        case 'ArrowRight':
        case 'n':
          e.preventDefault();
          nextStep();
          break;
        case 'ArrowLeft':
        case 'p':
          e.preventDefault();
          prevStep();
          break;
        case ' ':
          e.preventDefault();
          if (isSpeaking) {
            togglePause();
          } else {
            speak(currentStep.description);
          }
          break;
        case 'm':
          e.preventDefault();
          stopSpeaking();
          break;
        case 'Escape':
          e.preventDefault();
          skipTour();
          break;
      }
    };

    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [showTour, nextStep, prevStep, isSpeaking, togglePause, speak, currentStep, stopSpeaking, skipTour]);

  // Auto-navigate, speak, and highlight when step changes
  useEffect(() => {
    if (!showTour) return;
    
    const step = TOUR_STEPS[currentStepIndex];
    if (!step) return;

    // Navigate if needed
    if (step.page !== location.pathname) {
      navigate(step.page);
    }

    // Speak and move Bam after a short delay
    const speakTimeout = setTimeout(() => {
      speak(step.description);
      moveMascotToElement(step.element);
    }, step.page !== location.pathname ? 600 : 300);

    // Highlight element if specified
    let highlightTimeout: NodeJS.Timeout;
    if (step.element) {
      highlightTimeout = setTimeout(() => {
        const el = document.querySelector(step.element!);
        if (el) {
          el.scrollIntoView({ behavior: "smooth", block: "center" });
          el.classList.add("tour-highlight");
          setTimeout(() => el.classList.remove("tour-highlight"), 3000);
        }
      }, step.page !== location.pathname ? 800 : 400);
    }

    return () => {
      clearTimeout(speakTimeout);
      if (highlightTimeout) clearTimeout(highlightTimeout);
    };
  }, [showTour, currentStepIndex, location.pathname, navigate, speak, moveMascotToElement]);

  // Dismiss hint after 5 seconds
  useEffect(() => {
    if (!showTour || !showHint) return;
    const timer = setTimeout(() => setShowHint(false), 6000);
    return () => clearTimeout(timer);
  }, [showTour, showHint]);

  // Drag handlers
  const handleMouseDown = useCallback((e: React.MouseEvent) => {
    isDraggingRef.current = true;
    const rect = (e.currentTarget.closest('[data-tour-panel]') as HTMLElement)?.getBoundingClientRect();
    if (rect) {
      dragOffsetRef.current = { x: e.clientX - rect.left, y: e.clientY - rect.top };
    }
    const handleMouseMove = (ev: MouseEvent) => {
      if (!isDraggingRef.current) return;
      setDragPosition({
        x: Math.max(0, Math.min(window.innerWidth - 100, ev.clientX - dragOffsetRef.current.x)),
        y: Math.max(0, Math.min(window.innerHeight - 60, ev.clientY - dragOffsetRef.current.y)),
      });
      if (!isCollapsed) setIsCollapsed(true);
    };
    const handleMouseUp = () => {
      isDraggingRef.current = false;
      window.removeEventListener('mousemove', handleMouseMove);
      window.removeEventListener('mouseup', handleMouseUp);
    };
    window.addEventListener('mousemove', handleMouseMove);
    window.addEventListener('mouseup', handleMouseUp);
  }, [isCollapsed]);

  // Auto-start countdown for first visit
  useEffect(() => {
    if (isFirstVisit && !showTour && location.pathname === "/" && !countdownPaused) {
      countdownRef.current = setInterval(() => {
        setCountdown(prev => {
          if (prev <= 1) {
            clearInterval(countdownRef.current!);
            startTour();
            return 0;
          }
          return prev - 1;
        });
      }, 1000);
    }

    return () => {
      if (countdownRef.current) {
        clearInterval(countdownRef.current);
      }
    };
  }, [isFirstVisit, showTour, location.pathname, countdownPaused, startTour]);

  const pauseCountdown = useCallback(() => {
    setCountdownPaused(true);
    if (countdownRef.current) {
      clearInterval(countdownRef.current);
    }
  }, []);

  // Floating demo button (always visible when tour not active)
  // Hidden on mobile to avoid blocking the menu button
  if (!showTour && !isFirstVisit && !hideFloatingDemoButton) {
    // Minimized state - small icon only
    if (isDemoMinimized) {
      return (
        <button
          onClick={() => setIsDemoMinimized(false)}
          className="fixed top-36 right-4 z-40 hidden md:flex w-10 h-10 bg-primary/80 text-primary-foreground rounded-full shadow-lg hover:scale-110 hover:bg-primary transition-all items-center justify-center"
          title="Show Demo Button"
        >
          <Play className="w-4 h-4" />
        </button>
      );
    }

    // Full demo button with minimize option - hidden on mobile
    return (
      <div className="fixed top-36 right-4 z-40 hidden md:flex items-center gap-1">
        <button
          onClick={() => {
            autoAdvanceRef.current = true;
            setIsFirstVisit(false);
            setShowTour(true);
            setCurrentStepIndex(0);
            if (location.pathname !== "/") {
              navigate("/");
            }
          }}
          className="flex items-center gap-2 px-4 py-2 bg-primary text-primary-foreground rounded-l-full shadow-lg hover:brightness-110 transition-all font-medium text-sm"
        >
          <Play className="w-4 h-4" />
          Live Demo
        </button>
        <button
          onClick={() => setIsDemoMinimized(true)}
          className="flex items-center justify-center w-8 h-[36px] bg-primary/80 text-primary-foreground rounded-r-full shadow-lg hover:bg-primary/60 transition-all"
          title="Minimize"
        >
          <X className="w-3.5 h-3.5" />
        </button>
      </div>
    );
  }

  // First visit prompt (before tour starts)
  if (isFirstVisit && !showTour && location.pathname === "/") {
    return (
      <div className="fixed inset-0 z-50 flex items-center justify-center bg-background/80 backdrop-blur-sm">
        <div 
          className="bg-card rounded-3xl border border-border shadow-elevated p-8 max-w-md mx-4 text-center animate-in zoom-in-95"
          onMouseEnter={pauseCountdown}
          onTouchStart={pauseCountdown}
        >
          <div className="relative w-24 h-24 mx-auto mb-4">
            <img 
              src={mascotImage} 
              alt="Bam the mascot" 
              className="w-full h-full object-contain animate-bounce"
            />
            {/* Pulsing attention indicator during countdown */}
            {!countdownPaused && countdown > 0 && (
              <span className="absolute -top-1 -right-1 flex h-5 w-5">
                <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-primary opacity-75" />
                <span className="relative inline-flex rounded-full h-5 w-5 bg-primary items-center justify-center text-[10px] font-bold text-primary-foreground">
                  {countdown}
                </span>
              </span>
            )}
          </div>
          <h2 className="text-2xl font-display font-bold text-foreground mb-3">
            Hey there! I'm Bam! 👋
          </h2>
          <p className="text-muted-foreground mb-4">
            Welcome to BamLead! I'm about to walk you through all the amazing features. Just sit back and let me show you around!
          </p>
          <p className="text-xs text-muted-foreground/70 mb-4">
            💡 You can turn off Bam anytime by clicking "Don't show this again" below
          </p>
          <div className="flex flex-col gap-3">
            <Button onClick={startTour} size="lg" className="w-full gap-2 relative overflow-hidden">
              {!countdownPaused && countdown > 0 && (
                <span 
                  className="absolute inset-0 bg-primary-foreground/20 origin-left animate-countdown"
                  style={{ 
                    animation: `countdown ${countdown}s linear forwards`,
                  }}
                />
              )}
              <Volume2 className="w-5 h-5 relative z-10" />
              <span className="relative z-10">
                {countdownPaused ? "Let's Go, Bam!" : `Starting in ${countdown}...`}
              </span>
            </Button>
            <Button onClick={() => { pauseCountdown(); skipTour(); }} variant="outline" size="lg" className="w-full">
              Skip for Now
            </Button>
            <button 
              onClick={() => { pauseCountdown(); disableTour(); }}
              className="text-sm text-muted-foreground hover:text-foreground transition-colors"
            >
              Don't show this again
            </button>
          </div>
        </div>
      </div>
    );
  }

  if (!showTour) return null;

  // Tour panel with Bam mascot walking
  return (
    <>
      {/* Tour highlight styles */}
      <style>{`
        .tour-highlight {
          position: relative;
          z-index: 40;
          animation: tour-pulse 2s ease-in-out;
        }
        @keyframes tour-pulse {
          0%, 100% { box-shadow: 0 0 0 0 rgba(20, 184, 166, 0); }
          50% { box-shadow: 0 0 0 8px rgba(20, 184, 166, 0.3); }
        }
        @keyframes bam-walk {
          0%, 100% { transform: translateY(0) rotate(0deg); }
          25% { transform: translateY(-8px) rotate(-3deg); }
          50% { transform: translateY(0) rotate(0deg); }
          75% { transform: translateY(-8px) rotate(3deg); }
        }
        @keyframes countdown {
          from { transform: scaleX(1); }
          to { transform: scaleX(0); }
        }
        @keyframes bam-bounce {
          0%, 100% { transform: translateY(0); }
          50% { transform: translateY(-5px); }
        }
        @keyframes template-slide {
          0% { transform: translateX(100%) scale(0.8); opacity: 0; }
          15% { transform: translateX(0) scale(1); opacity: 1; }
          85% { transform: translateX(0) scale(1); opacity: 1; }
          100% { transform: translateX(-100%) scale(0.8); opacity: 0; }
        }
        @keyframes template-float {
          0%, 100% { transform: translateY(0); }
          50% { transform: translateY(-8px); }
        }
        @keyframes orange-border-glow {
          0%, 100% { border-color: hsl(25 95% 53% / 0.6); box-shadow: 0 0 8px hsl(25 95% 53% / 0.3); }
          50% { border-color: hsl(25 95% 53% / 1); box-shadow: 0 0 20px hsl(25 95% 53% / 0.5), 0 0 40px hsl(25 95% 53% / 0.2); }
        }
      `}</style>

      {/* Email Template Preview Animation - Shows during email steps */}
      {(currentStep.id === "email-outreach" || currentStep.id === "lead-nurturing") && (
        <div className="fixed top-20 right-8 z-[55] pointer-events-none hidden md:block">
          <div className="relative">
            {/* Animated template cards */}
            <div className="flex flex-col gap-3">
              {/* Template 1 - Hero Style */}
              <div 
                className="w-64 bg-card rounded-xl border border-border shadow-elevated overflow-hidden animate-[template-float_3s_ease-in-out_infinite]"
                style={{ animationDelay: "0s" }}
              >
                <div className="h-16 bg-gradient-to-r from-cyan-500/30 to-blue-600/30 flex items-center justify-center relative">
                  <Rocket className="w-6 h-6 text-cyan-400" />
                  <div className="absolute top-2 right-2">
                    <Badge variant="secondary" className="text-[10px] px-1.5 py-0.5">Sales</Badge>
                  </div>
                </div>
                <div className="p-3">
                  <div className="h-2 w-3/4 bg-foreground/20 rounded mb-2" />
                  <div className="h-1.5 w-full bg-foreground/10 rounded mb-1" />
                  <div className="h-1.5 w-2/3 bg-foreground/10 rounded mb-2" />
                  <div className="h-5 w-16 bg-primary/30 rounded-md flex items-center justify-center">
                    <Send className="w-3 h-3 text-primary" />
                  </div>
                </div>
              </div>

              {/* Template 2 - Newsletter Style */}
              <div 
                className="w-64 bg-card rounded-xl border border-border shadow-elevated overflow-hidden animate-[template-float_3s_ease-in-out_infinite]"
                style={{ animationDelay: "0.5s" }}
              >
                <div className="h-10 bg-gradient-to-r from-emerald-500/30 to-teal-600/30 flex items-center px-3 gap-2">
                  <Mail className="w-4 h-4 text-emerald-400" />
                  <div className="h-1.5 w-16 bg-white/30 rounded" />
                  <Badge variant="secondary" className="text-[10px] px-1.5 py-0.5 ml-auto">Newsletter</Badge>
                </div>
                <div className="p-2 grid grid-cols-2 gap-2">
                  <div className="bg-foreground/5 rounded p-1.5">
                    <div className="h-6 bg-gradient-to-br from-emerald-500/20 to-teal-600/20 rounded mb-1" />
                    <div className="h-1 w-full bg-foreground/10 rounded" />
                  </div>
                  <div className="bg-foreground/5 rounded p-1.5">
                    <div className="h-6 bg-gradient-to-br from-emerald-500/20 to-teal-600/20 rounded mb-1" />
                    <div className="h-1 w-full bg-foreground/10 rounded" />
                  </div>
                </div>
              </div>

              {/* Template 3 - Promo Style */}
              <div 
                className="w-64 bg-card rounded-xl border border-border shadow-elevated overflow-hidden animate-[template-float_3s_ease-in-out_infinite]"
                style={{ animationDelay: "1s" }}
              >
                <div className="h-14 bg-gradient-to-r from-orange-500/30 to-red-500/30 flex flex-col items-center justify-center relative">
                  <Gift className="w-5 h-5 text-orange-400 mb-1" />
                  <div className="text-[9px] font-bold text-foreground/60">SPECIAL OFFER</div>
                  <Badge variant="secondary" className="text-[10px] px-1.5 py-0.5 absolute top-2 right-2">Promo</Badge>
                </div>
                <div className="p-3 flex flex-col items-center">
                  <div className="flex gap-0.5 mb-2">
                    <Star className="w-3 h-3 text-orange-400" />
                    <Star className="w-3 h-3 text-orange-400" />
                    <Star className="w-3 h-3 text-orange-400" />
                  </div>
                  <div className="h-5 w-20 bg-orange-500/30 rounded-full flex items-center justify-center">
                    <Zap className="w-3 h-3 text-orange-400" />
                  </div>
                </div>
              </div>
            </div>

            {/* Floating label */}
            <div className="absolute -top-8 left-0 right-0 text-center">
              <Badge className="bg-primary/90 text-primary-foreground px-3 py-1 animate-pulse">
                <Sparkles className="w-3 h-3 mr-1 inline" />
                60+ High-Converting Templates
              </Badge>
            </div>

            {/* AI indicator for nurturing step */}
            {currentStep.id === "lead-nurturing" && (
              <div className="absolute -left-16 top-1/2 -translate-y-1/2 flex flex-col items-center gap-1">
                <div className="w-8 h-8 rounded-full bg-accent/20 flex items-center justify-center animate-pulse">
                  <TrendingUp className="w-4 h-4 text-accent" />
                </div>
                <div className="w-px h-12 bg-accent/30" />
                <div className="w-8 h-8 rounded-full bg-accent/20 flex items-center justify-center animate-pulse" style={{ animationDelay: "0.3s" }}>
                  <Calendar className="w-4 h-4 text-accent" />
                </div>
                <div className="w-px h-12 bg-accent/30" />
                <div className="w-8 h-8 rounded-full bg-accent/20 flex items-center justify-center animate-pulse" style={{ animationDelay: "0.6s" }}>
                  <Users className="w-4 h-4 text-accent" />
                </div>
                <div className="text-[10px] text-accent font-medium mt-1">Sequences</div>
              </div>
            )}
          </div>
        </div>
      )}

      {/* Bam Mascot - Walking to each section */}
      <div 
        className="fixed z-[60] pointer-events-none transition-all duration-1000 ease-out"
        style={{
          left: `${mascotPosition.x}px`,
          top: `${mascotPosition.y}px`,
        }}
      >
        <div className={`relative ${isWalking ? 'animate-[bam-walk_0.4s_ease-in-out_infinite]' : isSpeaking ? 'animate-[bam-bounce_0.6s_ease-in-out_infinite]' : ''}`}>
          <img 
            src={mascotImage} 
            alt="Bam" 
            className="w-20 h-20 object-contain drop-shadow-lg"
          />
          {/* Speech indicator */}
          {isSpeaking && (
            <div className="absolute -top-2 -right-2 w-6 h-6 bg-primary rounded-full flex items-center justify-center animate-pulse">
              <Volume2 className="w-3 h-3 text-primary-foreground" />
            </div>
          )}
        </div>
      </div>

      {/* Tour Panel - Draggable & Collapsible */}
      <div
        data-tour-panel
        className="fixed z-50 transition-all duration-300 ease-out"
        style={dragPosition ? {
          left: `${dragPosition.x}px`,
          top: `${dragPosition.y}px`,
        } : {
          bottom: '1rem',
          left: '1rem',
        }}
      >
        {/* Collapsed state - small icon */}
        {isCollapsed ? (
          <button
            onClick={() => setIsCollapsed(false)}
            className="relative w-16 h-16 rounded-2xl bg-card border-2 shadow-elevated flex items-center justify-center cursor-pointer hover:scale-110 transition-transform"
            style={{ animation: 'orange-border-glow 2s ease-in-out infinite', borderColor: 'hsl(25 95% 53% / 0.8)' }}
            title="Click to expand tour guide"
            onMouseDown={handleMouseDown}
          >
            <img src={mascotImage} alt="Bam" className="w-10 h-10 object-contain" />
            {isSpeaking && (
              <div className="absolute -top-1 -right-1 w-4 h-4 bg-primary rounded-full flex items-center justify-center">
                <Volume2 className="w-2.5 h-2.5 text-primary-foreground" />
              </div>
            )}
          </button>
        ) : (
        <div
          className="w-[calc(100vw-2rem)] max-w-md rounded-2xl bg-card shadow-elevated overflow-hidden relative border-2 max-h-[70vh] overflow-y-auto"
          style={{ animation: 'orange-border-glow 2s ease-in-out infinite', borderColor: 'hsl(25 95% 53% / 0.8)' }}
        >
          {/* Drag handle bar */}
          <div
            onMouseDown={handleMouseDown}
            className="h-6 bg-secondary/50 flex items-center justify-center cursor-grab active:cursor-grabbing select-none"
          >
            <div className="w-10 h-1 rounded-full bg-muted-foreground/30" />
          </div>

          {/* Hint message at beginning */}
          {showHint && currentStepIndex === 0 && (
            <div className="bg-orange-500/10 border-b border-orange-500/20 px-4 py-2 text-xs text-center" style={{ color: 'hsl(25 95% 53%)' }}>
              💡 Drag this box to move it, or click it when small to expand. Click the minimize button to shrink it!
            </div>
          )}
          {/* Progress bar */}
          <div className="h-1.5 bg-secondary">
            <div 
              className="h-full bg-gradient-to-r from-primary to-accent transition-all duration-500 ease-out"
              style={{ width: `${((currentStepIndex + 1) / TOUR_STEPS.length) * 100}%` }}
            />
          </div>

          {/* Step indicators */}
          <div className="flex items-center justify-center gap-1 md:gap-1.5 py-2 md:py-3 border-b border-border/50 flex-wrap">
            {TOUR_STEPS.map((step, index) => (
              <button
                key={step.id}
                onClick={() => goToStep(index, true)}
                className={`group relative flex items-center justify-center transition-all duration-300 ${
                  index === currentStepIndex 
                    ? 'scale-110' 
                    : 'hover:scale-105'
                }`}
                title={step.title}
              >
                <div className={`w-2.5 h-2.5 rounded-full transition-all duration-300 ${
                  index < currentStepIndex 
                    ? 'bg-primary' 
                    : index === currentStepIndex 
                      ? 'bg-accent ring-2 ring-accent/30 ring-offset-1 ring-offset-card' 
                      : 'bg-muted-foreground/30'
                }`} />
                {/* Tooltip on hover */}
                <div className="absolute -top-8 left-1/2 -translate-x-1/2 opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none">
                  <div className="bg-foreground text-background text-[10px] px-2 py-1 rounded whitespace-nowrap font-medium shadow-lg">
                    {index + 1}. {step.title.replace(/[🎉🚀]/gu, '').trim()}
                  </div>
                </div>
              </button>
            ))}
          </div>

          <div className="p-3 md:p-6">
            {/* Header */}
            <div className="flex items-start justify-between gap-4 mb-4">
              <div className="flex items-center gap-3">
                <img 
                  src={mascotImage} 
                  alt="Bam" 
                  className={`w-8 h-8 md:w-12 md:h-12 object-contain ${isSpeaking ? 'animate-pulse' : ''}`}
                />
                <div>
                  <Badge variant="outline" className="mb-1">
                    Step {currentStepIndex + 1} of {TOUR_STEPS.length}
                  </Badge>
                  <h3 className="font-display font-bold text-foreground">
                    {currentStep.title}
                  </h3>
                </div>
              </div>
              <div className="flex items-center gap-1">
                <Button 
                  variant="ghost" 
                  size="icon" 
                  onClick={() => setIsCollapsed(true)}
                  className="shrink-0"
                  title="Minimize"
                >
                  <ChevronDown className="w-5 h-5" />
                </Button>
                <Button 
                  variant="ghost" 
                  size="icon" 
                  onClick={skipTour}
                  className="shrink-0"
                >
                  <X className="w-5 h-5" />
                </Button>
              </div>
            </div>

            {/* Description with optional subtitles styling */}
            {showSubtitles && (
              <div className="bg-secondary/50 rounded-lg p-2 md:p-3 mb-3 md:mb-4 border-l-2 border-primary max-h-[25vh] overflow-y-auto">
                <p className="text-foreground text-xs md:text-sm leading-relaxed">
                  {currentStep.description}
                </p>
              </div>
            )}
            {!showSubtitles && (
              <p className="text-muted-foreground text-xs md:text-sm leading-relaxed mb-3 md:mb-4 max-h-[25vh] overflow-y-auto">
                {currentStep.description}
              </p>
            )}

            {/* Controls */}
            <div className="flex items-center justify-between gap-1 md:gap-2 flex-wrap">
              <div className="flex items-center gap-1 md:gap-2">
                <Button
                  variant="outline"
                  size="sm"
                  onClick={prevStep}
                  disabled={currentStepIndex === 0}
                  className="gap-1"
                >
                  <ChevronLeft className="w-4 h-4" />
                  Back
                </Button>
                <Button
                  variant="outline"
                  size="icon"
                  onClick={isSpeaking ? togglePause : () => speak(currentStep.description)}
                  className="h-8 w-8"
                >
                  {isSpeaking && !isPaused ? (
                    <Pause className="w-4 h-4" />
                  ) : (
                    <Play className="w-4 h-4" />
                  )}
                </Button>
                <Button
                  variant="ghost"
                  size="icon"
                  onClick={stopSpeaking}
                  className="h-8 w-8 hidden md:flex"
                  disabled={!isSpeaking}
                >
                  <VolumeX className="w-4 h-4" />
                </Button>

                {/* Voice Settings Popover */}
                <Popover open={showVoiceSettings} onOpenChange={setShowVoiceSettings}>
                  <PopoverTrigger asChild>
                    <Button
                      variant="ghost"
                      size="icon"
                      className="h-8 w-8 hidden md:flex"
                      title="Voice Settings"
                    >
                      <Settings2 className="w-4 h-4" />
                    </Button>
                  </PopoverTrigger>
                  <PopoverContent className="w-80" align="start" side="top">
                    <div className="space-y-4">
                      <div className="flex items-center justify-between">
                        <h4 className="font-semibold text-sm flex items-center gap-2">
                          <Mic2 className="w-4 h-4" />
                          Voice Settings
                        </h4>
                        <Button 
                          size="sm" 
                          variant="outline"
                          onClick={testVoice}
                          disabled={isTestingVoice}
                          className="h-7 text-xs"
                        >
                          {isTestingVoice ? "Playing..." : "Test Voice"}
                        </Button>
                      </div>

                      {/* Voice Selector */}
                      <div className="space-y-2">
                        <Label className="text-xs text-muted-foreground">Select Voice</Label>
                        <div className="max-h-40 overflow-y-auto space-y-1 pr-2">
                          {/* Premium Voices */}
                          {availableVoices.filter(v => v.category === 'premium').length > 0 && (
                            <>
                              <p className="text-xs font-medium text-primary mt-2 mb-1">✨ Premium</p>
                              {availableVoices.map((voiceOption, idx) => 
                                voiceOption.category === 'premium' && (
                                  <button
                                    key={idx}
                                    onClick={() => setSelectedVoiceIndex(idx)}
                                    className={`w-full text-left px-2 py-1.5 rounded text-xs flex items-center justify-between transition-colors ${
                                      selectedVoiceIndex === idx 
                                        ? 'bg-primary/20 text-primary' 
                                        : 'hover:bg-secondary'
                                    }`}
                                  >
                                    <span>{voiceOption.label}</span>
                                    {selectedVoiceIndex === idx && <Check className="w-3 h-3" />}
                                  </button>
                                )
                              )}
                            </>
                          )}
                          
                          {/* Natural Voices */}
                          {availableVoices.filter(v => v.category === 'natural').length > 0 && (
                            <>
                              <p className="text-xs font-medium text-accent mt-2 mb-1">🎯 Natural</p>
                              {availableVoices.map((voiceOption, idx) => 
                                voiceOption.category === 'natural' && (
                                  <button
                                    key={idx}
                                    onClick={() => setSelectedVoiceIndex(idx)}
                                    className={`w-full text-left px-2 py-1.5 rounded text-xs flex items-center justify-between transition-colors ${
                                      selectedVoiceIndex === idx 
                                        ? 'bg-primary/20 text-primary' 
                                        : 'hover:bg-secondary'
                                    }`}
                                  >
                                    <span>{voiceOption.label}</span>
                                    {selectedVoiceIndex === idx && <Check className="w-3 h-3" />}
                                  </button>
                                )
                              )}
                            </>
                          )}
                          
                          {/* Standard Voices */}
                          {availableVoices.filter(v => v.category === 'standard').length > 0 && (
                            <>
                              <p className="text-xs font-medium text-muted-foreground mt-2 mb-1">📢 Standard</p>
                              {availableVoices.map((voiceOption, idx) => 
                                voiceOption.category === 'standard' && (
                                  <button
                                    key={idx}
                                    onClick={() => setSelectedVoiceIndex(idx)}
                                    className={`w-full text-left px-2 py-1.5 rounded text-xs flex items-center justify-between transition-colors ${
                                      selectedVoiceIndex === idx 
                                        ? 'bg-primary/20 text-primary' 
                                        : 'hover:bg-secondary'
                                    }`}
                                  >
                                    <span>{voiceOption.label}</span>
                                    {selectedVoiceIndex === idx && <Check className="w-3 h-3" />}
                                  </button>
                                )
                              )}
                            </>
                          )}
                        </div>
                      </div>

                      {/* Speed Control */}
                      <div className="space-y-2">
                        <div className="flex items-center justify-between">
                          <Label className="text-xs text-muted-foreground">Speed</Label>
                          <span className="text-xs text-muted-foreground">{speechRate.toFixed(2)}x</span>
                        </div>
                        <Slider
                          value={[speechRate]}
                          onValueChange={([value]) => setSpeechRate(value)}
                          min={0.5}
                          max={1.5}
                          step={0.05}
                          className="w-full"
                        />
                        <div className="flex justify-between text-xs text-muted-foreground">
                          <span>Slow</span>
                          <span>Fast</span>
                        </div>
                      </div>

                      {/* Subtitles Toggle */}
                      <div className="flex items-center justify-between">
                        <Label className="text-xs flex items-center gap-2">
                          <Captions className="w-4 h-4" />
                          Show Subtitles
                        </Label>
                        <Switch
                          checked={showSubtitles}
                          onCheckedChange={setShowSubtitles}
                        />
                      </div>

                      {/* Keyboard Shortcuts */}
                      <div className="pt-2 border-t border-border">
                        <p className="text-xs text-muted-foreground flex items-center gap-1 mb-2">
                          <Keyboard className="w-3 h-3" />
                          Keyboard Shortcuts
                        </p>
                        <div className="grid grid-cols-2 gap-1 text-xs">
                          <span className="text-muted-foreground">← → or N/P</span>
                          <span>Navigate</span>
                          <span className="text-muted-foreground">Space</span>
                          <span>Play/Pause</span>
                          <span className="text-muted-foreground">M</span>
                          <span>Mute</span>
                          <span className="text-muted-foreground">Esc</span>
                          <span>Exit Tour</span>
                        </div>
                      </div>
                    </div>
                  </PopoverContent>
                </Popover>
              </div>

              <div className="flex items-center gap-1 md:gap-2">
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={skipTour}
                  className="text-muted-foreground"
                >
                  <SkipForward className="w-4 h-4 mr-1" />
                  Skip Tour
                </Button>
                <Button
                  size="sm"
                  onClick={nextStep}
                  className="gap-1"
                >
                  {currentStepIndex === TOUR_STEPS.length - 1 ? "Finish" : "Next"}
                  <ChevronRight className="w-4 h-4" />
                </Button>
              </div>
            </div>
          </div>
        </div>
        )}
      </div>
    </>
  );
}
